# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
  errors:
    # 警告は出したくない
    todo: ignore

linter:
  rules:
    always_use_package_imports: true