targets:
  $default:
    builders:
      riverpod_generator:
        options:
          provider_family_name_suffix: "ProviderFamily"
      build_version:
        options:
          output: lib/resources/version.dart