name: flutter_k9i_portfolio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.2.0
  riverpod_annotation: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  custom_lint: ^0.2.5
  riverpod_lint: ^1.0.1
  riverpod_generator: ^1.2.0
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true
