name: flutter_k9i_portfolio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  hooks_riverpod: ^2.2.0
  intl: ^0.17.0
  riverpod_annotation: ^1.2.1
  simple_icons: ^7.10.0
  text_style_preview: ^0.1.3
  url_launcher: ^6.1.10
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  custom_lint: ^0.2.5
  riverpod_lint: ^1.0.1
  riverpod_generator: ^1.2.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  flutter_gen_runner: ^5.2.0
  flutter_gen: ^5.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
  - assets/images/

  fonts:
  - family: NotoSansJP
    fonts:
      - asset: assets/fonts/NotoSansJP-Regular.otf
  - family: NotoColorEmoji
    fonts:
      - asset: assets/fonts/NotoColorEmoji-Regular.ttf

# flutter_genの生成場所を変更
flutter_gen:
  output: lib/resources