name: flutter_k9i_portfolio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  hooks_riverpod: ^2.3.1
  intl: ^0.17.0
  package_info_plus: ^3.0.3
  riverpod_annotation: ^2.0.1
  shared_preferences: ^2.0.18
  simple_icons: ^7.10.0
  text_style_preview: ^0.1.3
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  flutter_gen: ^5.2.0
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  grinder: ^0.9.3
  riverpod_generator: ^2.1.2
  riverpod_lint: ^1.1.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf

# flutter_genの生成場所を変更
flutter_gen:
  output: lib/resources

flutter_icons:
  image_path: "assets/icons/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
