name: flutter_k9i_portfolio
description: A new Flutter project.
publish_to: "none"
version: 0.2.3

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  go_router: ^6.5.2
  hooks_riverpod: ^2.3.2
  intl: ^0.17.0
  riverpod_annotation: ^2.0.2
  shared_preferences: ^2.1.0
  simple_icons: ^7.10.0
  text_style_preview: ^0.1.4
  url_launcher: ^6.1.10

dev_dependencies:
  altive_lints: any
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  dart_openai: ^1.9.1
  dependency_validator: ^3.2.2
  dotenv: ^4.1.0
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  grinder: ^0.9.3
  k9i_cli: ^1.0.0
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf

# flutter_genの生成場所を変更
flutter_gen:
  output: lib/resources

flutter_icons:
  image_path: "assets/icons/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
