name: Flutter Analyze

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  flutter-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wasabeef/import-asdf-tool-versions-action@v1.0.1
        id: asdf
      - name: Install Flutter
        run: ./.github/workflows/scripts/install-flutter.sh ${{ steps.asdf.outputs.flutter }}
      - run: flutter pub get
      - name: Run analyzer
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true
          annotate: true
          annotate-only: false
          working-directory: ./lib/
      - run: dart pub global activate custom_lint
      - name: Run custom_lint
        run: custom_lint
