name: Flutter Analyze

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  flutter-analyze:
    runs-on: ubuntu-latest

    steps:
      # 準備
      - uses: actions/checkout@v3

      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV
      - name: Install dependencies
        run: flutter pub get
      - run: dart pub global activate custom_lint

      # 実行
      - name: Run analyzer
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true
          annotate: true
          annotate-only: false
          working-directory: ./lib/
      - name: Run custom_lint
        run: custom_lint
